name: iOS Build (Unsigned)

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Xcode
        run: |
          sudo gem install cocoapods
          pod repo update
          pod install

      - name: Build iOS App (Unsigned)
        run: |
          flutter build ios --no-codesign  # Building without code signing

      - name: Export .ipa
        run: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -allowProvisioningUpdates

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa
