name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter (using a version that supports Dart SDK 3.5.1 or higher)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Use Flutter version that supports Dart 3.5.1+
          channel: stable
          architecture: x64  # or ARM64 if needed

      # Step 3: Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Step 4: Install CocoaPods dependencies for iOS (only required for iOS builds)
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      # Step 5: Build iOS app without code signing (skip if not building for iOS)
      - name: Build iOS app without code signing
        run: flutter build ios --no-codesign

      # Step 6: Archive the iOS build and export .ipa file (skip if not building for iOS)
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -allowProvisioningUpdates

      # Step 7: Test the app on an iOS Simulator (optional, only if needed for iOS testing)
      - name: Test on iOS Simulator
        run: |
          device=$(xcrun simctl list devices available | grep -m1 'iPhone' | awk -F '[()]' '{print $2}')
          flutter test --device-id=$device

      # Step 8: Upload .ipa as a build artifact (optional, skip if not building iOS)
      - name: Upload .ipa Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
