name: iOS Flutter Build and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Flutter iOS app using GitHub Actions
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Set up Flutter on the macOS machine
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Ensure the iOS environment is set up (CocoaPods)
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      # Build the iOS app without code signing
      - name: Build iOS app without code signing
        run: flutter build ios --no-codesign

      # Export .ipa file
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -allowProvisioningUpdates

      # Test using iOS Simulator
      - name: Test on iOS Simulator
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          flutter test

      # Upload the .ipa file as an artifact
      - name: Upload .ipa Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
